---
#- name: Trigger Heat Orchestration Template(HOT) file
#  command: openstack stack create -t files/hot.yaml -e files/env.yaml "{{ project_id }}_stack5555"

- name: Wait until the stack success
  command: bash -c "openstack stack list | grep {{ project_id }} | awk '{ print $6 }'"
  register: result
  until: result['stdout'] == "CREATE_COMPLETE"
  retries: 10
  delay: 6

- name: Get kubemaster's ip
  command: bash -c "openstack stack show {{ project_id }} | grep 10.33.128 | awk '{print $4}'"
  register: ip_address

- name: Add kubemaster to host list
  add_host: name="{{ ip_address['stdout'] }}" groups=infra
