---
- name: Install docker py
  command: bash -c "pip install docker-py==1.9.0 --force-reinstall"
#  pip: name=docker-py version=1.9.0 state=forcereinstall
- include: port_check.yml
- include: pull.yml
- include: run.yml
